export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_LOADING = 'LOAD_CATEGORIES_LOADING';
export const LOAD_CATEGORIES_ERROR = 'LOAD_CATEGORIES_ERROR';

export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_PRODUCTS_LOADING = 'LOAD_PRODUCTS_LOADING';
export const LOAD_PRODUCTS_ERROR = 'LOAD_PRODUCTS_ERROR';
