export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_LOADING = 'LOAD_CATEGORIES_LOADING';
export const LOAD_CATEGORIES_ERROR = 'LOAD_CATEGORIES_ERROR';

export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_PRODUCTS_LOADING = 'LOAD_PRODUCTS_LOADING';
export const LOAD_PRODUCTS_ERROR = 'LOAD_PRODUCTS_ERROR';

export const LOAD_SINGLE_PRODUCT_SUCCESS = 'LOAD_SINGLE_PRODUCT_SUCCESS';
export const LOAD_SINGLE_PRODUCT_LOADING = 'LOAD_SINGLE_PRODUCT_LOADING';
export const LOAD_SINGLE_PRODUCT_ERROR = 'LOAD_SINGLE_PRODUCT_ERROR';

export const LOAD_SINGLE_PRODUCT_IMAGE_SUCCESS = 'LOAD_SINGLE_PRODUCT_IMAGE_SUCCESS';
export const LOAD_SINGLE_PRODUCT_IMAGE_LOADING = 'LOAD_SINGLE_PRODUCT_IMAGE_LOADING';
export const LOAD_SINGLE_PRODUCT_IMAGE_ERROR = 'LOAD_SINGLE_PRODUCT_IMAGE_ERROR';

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_LOADING = 'LOAD_USER_LOADING';
export const LOAD_USER_ERROR = 'LOAD_USER_ERROR';

export const LOAD_CART_SUCCESS = 'LOAD_CART_SUCCESS';
export const LOAD_CART_LOADING = 'LOAD_CART_LOADING';
export const LOAD_CART_ERROR = 'LOAD_CART_ERROR';

export const ADD_CART_ITEM_SUCCESS = 'ADD_CART_ITEM_SUCCESS';
export const ADD_CART_ITEM_LOADING = 'ADD_CART_ITEM_LOADING';
export const ADD_CART_ITEM_ERROR = 'ADD_CART_ITEM_ERROR';

export const REMOVE_CART_ITEM_SUCCESS = 'REMOVE_CART_ITEM_SUCCESS';
export const REMOVE_CART_ITEM_LOADING = 'REMOVE_CART_ITEM_LOADING';
export const REMOVE_CART_ITEM_ERROR = 'REMOVE_CART_ITEM_ERROR';

export const UPDATE_CART_ITEM_SUCCESS = 'UPDATE_CART_ITEM_SUCCESS';
export const UPDATE_CART_ITEM_LOADING = 'UPDATE_CART_ITEM_LOADING';
export const UPDATE_CART_ITEM_ERROR = 'UPDATE_CART_ITEM_ERROR';

export const OPEN_CART_TOGGLED = 'OPEN_CART_TOGGLED';

export const LOAD_GLOBAL_SUCCESS = 'LOAD_GLOBAL_SUCCESS';
export const LOAD_GLOBAL_ERROR = 'LOAD_GLOBAL_ERROR';
export const LOAD_GLOBAL_LOADING = 'LOAD_GLOBAL_LOADING';

export const LOAD_ORDERS_SUCCESS = 'LOAD_ORDERS_SUCCESS';
export const LOAD_ORDERS_ERROR = 'LOAD_ORDERS_ERROR';
export const LOAD_ORDERS_LOADING = 'LOAD_ORDERS_LOADING';

export const SAVE_GLOBAL_SELECTED_SUCCESS = 'SAVE_GLOBAL_SELECTED_SUCCESS';
