export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_LOADING = 'LOAD_CATEGORIES_LOADING';
export const LOAD_CATEGORIES_ERROR = 'LOAD_CATEGORIES_ERROR';

export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_PRODUCTS_LOADING = 'LOAD_PRODUCTS_LOADING';
export const LOAD_PRODUCTS_ERROR = 'LOAD_PRODUCTS_ERROR';

export const LOAD_SINGLE_PRODUCT_SUCCESS = 'LOAD_SINGLE_PRODUCT_SUCCESS';
export const LOAD_SINGLE_PRODUCT_LOADING = 'LOAD_SINGLE_PRODUCT_LOADING';
export const LOAD_SINGLE_PRODUCT_ERROR = 'LOAD_SINGLE_PRODUCT_ERROR';

export const LOAD_SINGLE_PRODUCT_IMAGE_SUCCESS = 'LOAD_SINGLE_PRODUCT_IMAGE_SUCCESS';
export const LOAD_SINGLE_PRODUCT_IMAGE_LOADING = 'LOAD_SINGLE_PRODUCT_IMAGE_LOADING';
export const LOAD_SINGLE_PRODUCT_IMAGE_ERROR = 'LOAD_SINGLE_PRODUCT_IMAGE_ERROR';

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_LOADING = 'LOAD_USER_LOADING';
export const LOAD_USER_ERROR = 'LOAD_USER_ERROR';

